### ISSUE TITLE
iPhone XS Max showing black front camera 

### ISSUE THREAD

**Issue by Shamsudeen53** [MillzyDev/MillzysMod#7]
**Description:** <br>
(What is the problem?)

**Steps to Reproduce:** <br>
(Your goto way to recreate this bug.) <br>
1. <br>
2. <br>
3.

**Expected Behaviour:** <br>
(What was supposed to happen?)

**Actual Behaviour:** <br>
(What actually happened?)

**Evidence:** <br>
(If possible, please put any screenshots and/or videos of the bug here.)

**Comment by Shamsudeen53** [comment]
After updating to the new version 16.2 my front camera doesn’t work anymore showing black screen

**Comment by Shamsudeen53** [comment]
![Uploading 3B4F7350-6DCF-492A-B94A-833C1800ACF0.png…]()

**Comment by MillzyDev** [comment]
I will be closing this; it is not relevant to the application. Nor is there a release for this program yet, on which the bug could occur.
